name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Client/**"

  push:
    branches:
      - main
      - develop
    paths:
      - "Client/**"

permissions:
  contents: read

jobs:
  frontend:
    name: Build Frontend

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
